export const IPC_CHANNELS = {
  appInfo: "app:info",
  projectsChoose: "projects:choose",
  projectsList: "projects:list",
  projectsRemove: "projects:remove",
  projectsReveal: "projects:reveal",
  conversationsList: "conversations:list",
  conversationsHistory: "conversations:history",
  conversationsRemove: "conversations:remove",
  agentsList: "agents:list",
  agentsRefresh: "agents:refresh",
  agentsModels: "agents:models",
  attachmentsChoose: "attachments:choose",
  attachmentsAdd: "attachments:add",
  systemOpenLink: "system:open-link",
  sessionsSend: "sessions:send",
  sessionsCancel: "sessions:cancel",
  sessionsRunFake: "sessions:run-fake",
  sessionsEvent: "sessions:event",
  permissionsRespond: "permissions:respond",
  routerPreview: "router:preview",
  workflowsRun: "workflows:run",
  workflowsEvent: "workflows:event",
  settingsRolesGet: "settings:roles:get",
  settingsRolesSave: "settings:roles:save",
  settingsRolesAcknowledge: "settings:roles:acknowledge",
  diagnosticsExport: "diagnostics:export",
} as const;
