export const IPC_CHANNELS = {
  appInfo: "app:info",
  projectsChoose: "projects:choose",
  projectsList: "projects:list",
  projectsRemove: "projects:remove",
  projectsReveal: "projects:reveal",
  conversationsList: "conversations:list",
  conversationsHistory: "conversations:history",
  conversationsRemove: "conversations:remove",
  agentsList: "agents:list",
  agentsRefresh: "agents:refresh",
  agentsModels: "agents:models",
  filesSearch: "files:search",
  attachmentsChoose: "attachments:choose",
  attachmentsAdd: "attachments:add",
  systemOpenLink: "system:open-link",
  sessionsSend: "sessions:send",
  sessionsCancel: "sessions:cancel",
  sessionsRunFake: "sessions:run-fake",
  sessionsEvent: "sessions:event",
  permissionsRespond: "permissions:respond",
  questionsRespond: "questions:respond",
  workflowsEvent: "workflows:event",
  settingsAgentsGet: "settings:agents:get",
  settingsAgentsSave: "settings:agents:save",
  settingsAgentsAcknowledge: "settings:agents:acknowledge",
  diagnosticsExport: "diagnostics:export",
} as const;
